# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build-bare-release

on:
  fork:
    branches: [ "main" ]
    tags:
     - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    container: node:18
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Get Latest Tag
      id: get_id
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo: "::set-output name=latest_tag::$latest_tag"
        
    - name: Checkout Latest Tag
      run: git checkout ${{steps.get_tag.outputs.latest_tag}}
      
    - name: install-pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: |
          - args: [--frozen-lockfile]
  
    - name: build
      run: pnpm build

    - name: package
      run: ll
      
